

version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.66:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.66:9092 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 

    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
