version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=172.31.6.111:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.31.6.111:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "127.0.0.1:9092"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - internal_network

  admin-service:
    image: amirpoudel/sm-admin-service
    environment:
      - KAFKA_BROKER=172.31.6.111:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  gateway-service:
    image: amirpoudel/sm-gateway-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:6000/api/v1
      - INGESTION_SERVICE_URL=http://ingestion-service:5000/api/v1
      - RESULT_SERVICE_URL=http://result-service:7000/api/v1
      - USERS_SERVICE_URL=http://user-service:4000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  user-service:
    image: amirpoudel/sm-user-service
    environment:
      - MONGODB_URI=
    ports:
      - "40001:40001"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  auth-service:
    image: amirpoudel/sm-auth-service
    environment:
      - ACCESS_TOKEN_SECRET=
      - ACCESS_TOKEN_EXPIRES_IN=
      - GRPC_ENDPOINT=user-service:40001
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  ingestion-service:
    image: amirpoudel/sm-ingestion-service
    environment:
      - DATABASE_URL=
      - KAFKA_BROKER=172.31.6.111:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  model-service:
    image: amirpoudel/sm-model-service
    environment:
      - KAFKA_BROKER=172.31.6.111:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

  result-service:
    image: amirpoudel/sm-result-service
    environment:
      - DATABASE_URL=
      - KAFKA_BROKER=172.31.6.111:9092
      - REDIS_HOST=redis
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
