

version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.1
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_EXTERNAL=EXTERNAL
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_INTERNAL=INTERNAL
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper
