version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.68:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.68:9092 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  host:
    external: true
    
