version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.68:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.68:9092 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


  admin-service:
    image : amirpoudel/sm-admin-service
    depends_on:
      - kafka
      - zookeeper
    networks:
      - internal_network

  gateway-service:
    image: amirpoudel/sm-gateway-service
    environment:
      - AUTH_SERVICE_URL='http://auth-service:6000/api/v1'  # Use service name for inter-service comms
      - INGESTION_SERVICE_URL='http://ingestion-service:5000/api/v1'
      - RESULT_SERVICE_URL='http://result-service:7000/api/v1'
      - USERS_SERVICE_URL='http://user-service:4000/api/v1'
    depends_on:
      - auth-service
      #- ingestion-service
      #- result-service
      - user-service
    networks:
      - internal_network

  auth-service:
    image: amirpoudel/sm-auth-service
    environment:
      - ACCESS_TOKEN_SECRET=TYBADGAH%323438q467e234jsdfHAJSDA12324234124
      - ACCESS_TOKEN_EXPIRES_IN=30d
      - GRPC_ENDPOINT=0.0.0.0:40001
    networks:
      - internal_network

  user-service:
    image:  amirpoudel/sm-user-service
    environment:
      # - MONGODB_URI="mongodb+srv://rms-nodejs:Yw5ReVYTL0obliM6@cluster0.8rxpgkr.mongodb.net/sm-users?retryWrites=true&w=majority"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge